### ISSUE TITLE
Set location using page name

### ISSUE THREAD

**Issue by joaovpmamede** [StoutLogic/acf-builder#10]
Not sure if it's possible but would be great to have something like this:

![screenshot 2016-06-13 12 06 35](https://cloud.githubusercontent.com/assets/1040722/16003958/96ba5658-315f-11e6-8ed7-0e35aac5308c.jpg)

Would it be possible to set a location like this?
```
->setLocation('page', '==', 'home')
```

Well, I think we could do something like this:

```
$page = get_page_by_path('home');

$rows = new FieldsBuilder('rows');
$rows
  ->addText('title')
  ->setLocation('page', '==', $page->ID);
```

But there's probably a better way. (Not sure what ACF does internally)

**Comment by stevep** [comment]
This should work. You're right, ACF does use the page ID as the value of that dropdown when selecting a page by name. Depending on how your theme is set up, you may have better luck assigning fields to the template being used. Mostly so you don't have a hard coded database value dependencies (page id) in your code.

```php
$rows = new FieldsBuilder('rows');
$rows
  ->addText('title')
  ->setLocation('page_template', '==', 'template-home.php');
```

There isn't good documentation of all the options, (yet). The easiest way to see the possible values, is to look at the ACF dropdowns using your browser's inspector and see what it is using for the values.

**Comment by joaovpmamede** [comment]
Great! I'm now using the `get_page_by_path` and it's working just fine.

Btw, I shouldn't have created this issue, because it's not really an issue. 
Will start asking these type of questions on gitter.

Thanks again for the answer.

**Comment by stevep** [comment]
No prob!
