### ISSUE TITLE
[Question] Extend FieldsBuilder

### ISSUE THREAD

**Issue by stephanedemotte** [StoutLogic/acf-builder#112]
Hello,

I want to add a custom function to the list.
Whats can be the best way to do this ?
I try to extend `FieldsBuilder` 

```
use StoutLogic\AcfBuilder\FieldsBuilder;

class BaseFieldsBuilder extends FieldsBuilder {

  public function addSomethingCool($name, array $args = []) {

    // play with data

    return $this->addtext($name, $args);
  }

}
```

But when i try to use it

```
$test
  ->addTab('Test')
    ->addGroup('test')
      ->addImage('cover')
      ->addSomethingCool('title');
```

The field is created but not in the test group... It's like the function it's not "chainable"

Maybe there are an official way to add a custom function ?

Thanks !!

**Comment by Log1x** [comment]
```php
<?php

use StoutLogic\AcfBuilder\FieldsBuilder as FieldsBuilderBase;

class FieldsBuilder extends FieldsBuilderBase
{
    /**
     * @param string $name
     * @param array $args field configuration
     * @throws FieldNameCollisionException if name already exists.
     * @return FieldBuilder
     */
    public function addCode($name, array $args = [])
    {
        return $this->addField($name, 'acf_code_field', $args);
    }

    /**
     * @param string $name
     * @param array $args field configuration
     * @throws FieldNameCollisionException if name already exists.
     * @return FieldBuilder
     */
    public function addSidebar($name, array $args = [])
    {
        return $this->addField($name, 'sidebar_selector', $args);
    }
}
```

**Comment by stephanedemotte** [comment]
I got exactly the same result with your code.

The field don't follow the parent group.

Don't see any difference between your code and mine :)

Maybe you can be more explicit ?

Thanks !

**Comment by Log1x** [comment]
Hmm. Can't say I'm getting the same behavior, at least for my use-case.

Try returning `$this` in your `addSomethingCool()` method?

**Comment by stephanedemotte** [comment]
I've tried, nothing change, got the same bug :/

**Comment by stevep** [comment]
@stephanedemotte @Log1x The issue is using the custom addSomethingCool function in a group. The addGroup function returns an object of GroupBuilder class, which itself extends the original FieldsBuilder class, which won't have your custom function.

The easiest way to do it, is to create your own GroupBuilder class that extends GroupBuilder the original GroupBuilder, but in the constructor, set $this->fieldsBuilder to a new instance of your custom FieldsBuilder class. I end up doing this in my projects as well:

```
class CustomGroupBuilder extends GroupBuilder
{

    public function __construct($name, $type = 'group', $config = [])
    {
        parent::__construct($name, $type, $config);
        $this->fieldsBuilder = new CustomFieldsBuilder($name);
        $this->fieldsBuilder->setParentContext($this);
    }

}
```

And then in your custom FieldGroupBuilder, over write the addGroup function to return an instance of your CustomGroupBuilder class:

```
class CustomFieldsBuilder extends FieldsBuilder
{
    public function addGroup($name, array $args = [])
    {
        return $this->initializeField(new CustomGroupBuilder($name, 'group', $args));
    }

}
```

**Comment by stephanedemotte** [comment]
Great ! thanks,

I see the same issue with repeater.

I've done the same thing

```
class CustomRepeaterBuilder extends RepeaterBuilder {
  public function __construct($name, $type = 'repeater', $config = []) {
    parent::__construct($name, $type, $config);
    $this->fieldsBuilder = new CustomBuilder($name);
    $this->fieldsBuilder->setParentContext($this);
  }
}
```

```
class CustomBuilder extends FieldsBuilder {
  public function addRepeater($name, array $args = []) {
    return $this->initializeField(new CustomRepeaterBuilder($name, 'repeater', $args));
  }
}
```

Seem to work well, do you see any potential issue ?

Thanks again for you great work :)

**Comment by stevep** [comment]
No, I also do this in my everyday code as well. I'm using namespaces but FieldsBuilder here is actually an extended version of the original acf builder FieldsBuilder.

https://github.com/StoutLogic/understory-acf/blob/master/lib/RepeaterBuilder.php#L16-L21

https://github.com/StoutLogic/understory-acf/blob/master/lib/FieldsBuilder.php#L18-L26

**Comment by stephanedemotte** [comment]
I've try the same thing with flexibleContentBuilder but not work :)

```
class CustomFlexibleContentBuilder extends FlexibleContentBuilder {
  public function __construct($name, $type = 'flexible_content', $config = []) {
    parent::__construct($name, $type, $config);
    $this->fieldsBuilder = new CustomBuilder($name);
    $this->fieldsBuilder->setParentContext($this);
  }
}
```

```
  class CustomBuilder extends FieldsBuilder {
    public function addFlexibleContent($name, array $args = []) {
      return $this->initializeField(new CustomFlexibleContentBuilder($name, 'flexible_content', $args));
  }
}
```

I have to do it for addLayout instead ?

**Comment by stevep** [comment]
What are you passing to addLayout? 

If it something that is an instance of FieldsBuilder no change should be required. However if you're passing a config array, then yes you need to replace the addLayout function to instantiate a new CustomFieldsBuilder.

https://github.com/StoutLogic/acf-builder/blob/master/src/FlexibleContentBuilder.php#L86

Otherwise if you're passing in a CustomFieldsBuilder to addLayout, it should clone it just fine with no change required.

**Comment by stephanedemotte** [comment]
Ok it's seem to work with 

```
class CustomFlexibleContentBuilder extends FlexibleContentBuilder {
  public function __construct($name, $type = 'flexible_content', $config = []) {
    parent::__construct($name, $type, $config);
    $this->fieldsBuilder = new CustomBuilder($name);
    $this->fieldsBuilder->setParentContext($this);
  }

  public function addLayout($layout, $args = []) {
    if ($layout instanceof FieldsBuilder) {
      $layout = clone $layout;
    } else {
      $layout = new CustomBuilder($layout, $args);
    }

    $layout = $this->initializeLayout($layout, $args);
    $this->pushLayout($layout);

    return $layout;
  }
}
```

I added the addLayout function with `CustomBuilder`

Thanks again !
