### ISSUE TITLE
Duplicated fields values showing up in admin.

### ISSUE THREAD

**Issue by waustin** [StoutLogic/acf-builder#115]
I have 2 different field groups on a page, both have the field named *title*
```php
protected function create_page_header() {
        $page_header = new FieldsBuilder('page_header', ['menu_order' => 0]);
        $page_header
            ->addText('title')->setInstructions('Overides the WP Page Title. If blank the page title is used.')
            ->addText('parent_title')->setInstructions('Override parent page title that displays above the title.')
            ->addImage('background_image')
            ->addColorPicker('header_color')->setInstructions('Background overlay and title line color')
            ->setLocation('post_type', '==', 'page');

        // Build it
        acf_add_local_field_group($page_header->build());

    }
protected function create_resource_page_template_fields() {
 $featured_resources
            ->addText('title')->setRequired()
            ->addRepeater('resources', ['layout' => 'block'])
                ->addText('resource_name')->setRequired()
                ->addImage('logo')->setRequired()
                ->addTextarea('description')
                ->addUrl('link')
            ->endRepeater()
            ->setLocation('post_type', '==', 'page')->and('page_template', '==', 'page-templates/resources.php');

            acf_add_local_field_group($featured_resources->build());
}
```

If I  var_dump the block the field is being created with a unique keys
```php
["key"]=> string(23) "field_page_header_title" 
```

However when I edit the page in the admin. WP / ACF is only using the "last" defined  field on the page. It acts like the keys are not unique.

I am running a new WP / Bedrock install.

ACF Builder "1.9.0"
ACF Pro: 5.8.11

**Comment by stevep** [comment]
@waustin I believe the issue is with ACF itself. When saving values to the post_meta table in the database, it uses the ACF field name as the meta_key, not the ACF field key.

I just tried this using the ACF UI to double check, two field groups with 1 field each named title and it only saves the last value.

**Comment by stevep** [comment]
@waustin I've started to do the same thing in my projects in some cases

**Comment by matteodriussi** [comment]
i had the same issue. i was able to fix this by adding the key to the FieldsBuilder instantiation, like this:

`$project_data = new FieldsBuilder('Project data', ['key' => 'project_data']);`
