### ISSUE TITLE
No such function setInstructions after Repeater or Group

### ISSUE THREAD

**Issue by mortensassi** [StoutLogic/acf-builder#117]
If i want to set an instructions text after an repeater or group i get an error - how do i overcome this?

`Fatal error: Uncaught Exception: No such function: setInstructions in M:\Sites\MY_CLIENT\06-Dev\app\public\vendor\stoutlogic\acf-builder\src\ParentDelegationBuilder.php on line 69`

```php
<?php

namespace App;

use StoutLogic\AcfBuilder\FieldsBuilder;

$tabs = new FieldsBuilder('tabs');

$tabs
    ->addText('headline')
    ->addRepeater('tabs', ['label' => 'Tabbed content', 'layout' => 'block', 'button_label' => 'Add content'])
        ->addText('title')
        ->addTextarea('text')
        ->addUrl('link')
    ->endRepeater()
    ->setInstructions('test');

return $tabs;
```

**Comment by stevep** [comment]
@mortensassi I believe instructions have to be added to a field. You can use a message field (see: [addMessage](https://github.com/StoutLogic/acf-builder/wiki/field-types#message)) if there is no field in particular to add instruction text too.

**Comment by mortensassi** [comment]
Thanks @stevep  that makes sense! I have wrapped a Group around the fields which allows to set an instruction!
