### ISSUE TITLE
Getting syntax error on PHP7

### ISSUE THREAD

**Issue by ajien** [StoutLogic/acf-builder#122]
Parse error: syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE) in /vendor/doctrine/inflector/lib/Doctrine/Inflector/Language.php on line 9

**Comment by Jelmerkeij** [comment]
Which exact versions of Doctrine and PHP are installed? At least PHP 7.1 is required by Doctrine since 2017 https://www.doctrine-project.org/2017/07/25/php-7.1-requirement-and-composer.html
