### ISSUE TITLE
Message field not working

### ISSUE THREAD

**Issue by jnaklaas** [StoutLogic/acf-builder#124]
`$field->addMessage('message']);` results in an error. The field group is located in a custom gutenberg block. The gutenberg block can't load the acf fields - ajax request results in a 500 error.

Error message: "preg_match_all() expects parameter 2 to be string, array given"
file: "/wp/wp-includes/formatting.php", … }

**Comment by stevep** [comment]
`addMessage` requires 2 fields. The first one is the label, and the second is the actual message.

https://github.com/StoutLogic/acf-builder/blob/e46d0fb5770c96dbb97c13fc855cfbb88e10aed2/src/FieldsBuilder.php#L551

**Comment by jnaklaas** [comment]
Thanks @stevep. The Wiki page got me on the wrong foot. The documentation on the Message field type is wrong.
