### ISSUE TITLE
Support for WPGraphQL?

### ISSUE THREAD

**Issue by intelligence** [StoutLogic/acf-builder#129]
Anyone managed to get acf-builder to play nice with WPGraphQL / WPGraphQL ACF?
https://github.com/wp-graphql/wp-graphql-acf

Would be nice to be able to fields created with acf-builder to show up in the schema.

**Comment by newloong** [comment]
+1

**Comment by Log1x** [comment]
try setting `['show_in_graphql' => true]` on your fields

**Comment by intelligence** [comment]
Yup, that works, thanks @Log1x!

**Comment by yano1978** [comment]
@Log1x Hi sorry to bother on an already closed "issue", how should be exactly added in my fields [['show_in_graphql' => true]](https://github.com/wp-graphql/wp-graphql-acf/blob/develop/src/class-acfsettings.php#L60) ?
Thanks in advance!

**Comment by stevep** [comment]
@yano1978 Add it to the group config

You can do it when creating the FieldsBuilder

```php
$banner = new StoutLogic\AcfBuilder\FieldsBuilder('banner', [
    'show_in_graphql' => true,
]);
```

or you can do it after

```php
$banner = new StoutLogic\AcfBuilder\FieldsBuilder('banner');

...

$banner->setGroupConfig('show_in_graphql',true)
```

You can also set `graphql_field_name` if needed

**Comment by yano1978** [comment]
Hi @stevep and thanks for the quick reply and help. I have tried both options as you suggested but it doesn't seem to work?
<img width="605" alt="image" src="https://github.com/StoutLogic/acf-builder/assets/47816089/94840295-a937-4c5a-be9e-b39d70e68b18">
<img width="1087" alt="image" src="https://github.com/StoutLogic/acf-builder/assets/47816089/a2125fae-6630-4b1c-b6b6-7d4d0b146725">
![image](https://github.com/StoutLogic/acf-builder/assets/47816089/561502b6-fee9-4bda-a685-61d918ae8ee0)
Am I missing something?
Thank you!

**Comment by stevep** [comment]
To confirm: you have the WPGraphQL for Advanced Custom Fields plugin installed?

**Comment by yano1978** [comment]
Indeed these are plugins installed:

- **Advanced Custom Fields PRO** => Version 5.12.3
- **Advanced Custom Fields: Extended** => Version 0.8.9.3
- **WPGraphQL** => Version 1.17.0
- **WPGraphQL for Advanced Custom Fields** => Version 0.6.1

**Comment by yano1978** [comment]
Hi @stevep again, just to let you know that, after some more diggings into wp_graphl documentation, I have finally found out how to add it here [https://www.wpgraphql.com/docs/custom-post-types#filtering-an-existing-post-type](https://www.wpgraphql.com/docs/custom-post-types#filtering-an-existing-post-type)
Basically, for an already existing acf custom type, it's sufficient to add it with addfilter function into functions.php like in the example's link.
<img width="1438" alt="image" src="https://github.com/StoutLogic/acf-builder/assets/47816089/d205f15f-3b49-4e9c-9dfc-2b3a07f1acce">
I hope it might help someone else 😉
