### ISSUE TITLE
Using a loop to create conditions for a field

### ISSUE THREAD

**Issue by marcelo2605** [StoutLogic/acf-builder#140]
I'm not sure if it's possible, but I'm trying to figure out how to set some conditions from an array of values. 

```
->addTrueFalse('filter_taxonomy', [
        'label' => 'Filter by taxonomy?',
        'wrapper' => [
            'width' => '33%',
        ],
        'ui' => 1,
    ])
        ->conditional('load_content', '==', '1')
```

So basically I have a first condition and need to add some other "and" conditions where the values comes from a function.

**Comment by stevep** [comment]
You could save the field, or conditional to a variable and then add more conditionals to that. Basically since every function call in ACF Builder's fluent api return `$this`, you can grab a handle at any point.

So something like this should work.

```php

$builder = new FieldsBuilder('banner');

$builder
    ->addText('Title');

$filterTaxonomyField = $builder->addTrueFalse('filter_taxonomy', [
        'label' => 'Filter by taxonomy?',
        'wrapper' => [
            'width' => '33%',
        ],
        'ui' => 1,
    ]);

foreach($condition in $conditions) {
    $filterTaxonomyField
        ->conditional($condition, '==', '1');
}

return $builder->build();
```

**Comment by marcelo2605** [comment]
Thanks @stevep!
