### ISSUE TITLE
Php 8

### ISSUE THREAD

**Issue by seabiscuit90** [StoutLogic/acf-builder#156]
Any update on supporting php 8?

**Comment by mike-sheppard** [comment]
@muhammadtalha89 FWIW we're running this on php8.1 on a few production sites with no issues

**Comment by teppokoivula** [comment]
No issues with PHP 8.0 here. Everything seems to work just fine, and haven't seen any notices etc. either.

**Comment by michaelw85** [comment]
@Log1x you closed this with status "not planned". To prevent any confusion I've been running 8.3 for a long time without any issues. I think resolved would be more appropriate.
