### ISSUE TITLE
 Invalid argument supplied for foreach() in .../stoutlogic/acf-builder/src/Transform/RecursiveTransform.php on line 34 (v1.12.0)

### ISSUE THREAD

**Issue by timlogemann** [StoutLogic/acf-builder#160]
I am encountering a thrown error while trying to create a field group with a taxonomy field. I tried printing the $config variable in the `transform()` function of the RecursiveTransform class and it seems that at some point it tries to pass `0` as $config.

This is the full builder code:
```<?php
use StoutLogic\AcfBuilder\FieldsBuilder;


$builder = new FieldsBuilder('taxonomy', ['position' => 'side']);

$builder
	->addTaxonomy('theme', [
		'label' => 'Thema',
		'instructions' => '',
		'required' => 1,
		'conditional_logic' => 0,
		'wrapper' => [
			'width' => '',
			'class' => '',
			'id' => '',
		],
		'taxonomy' => 'theme',
		'field_type' => 'select',
		'allow_null' => 0,
		'add_term' => 0,
		'save_terms' => 0,
		'load_terms' => 0,
		'return_format' => 'id',
		'multiple' => 0,
	])
	->setLocation('post_type', '==', 'excercise');

add_action('acf/init', function () use ($builder) {
	acf_add_local_field_group($builder->build());
});
```

It really has to do with the taxonomy field, because as soon as I remove the addTaxonomy the error message disappears.

**Comment by timlogemann** [comment]
Good hunch!
that did remove the error. I copied this exact field code from the documentation wiki, where this `'conditional_logic' => 0` was included. Maybe it should be removed from there? If you agree I can make a PR for this

**Comment by stevep** [comment]
@timlogemann thanks for pointing that out. I removed the conditional_logic key from the examples and added a note that says these are the default attribute values for reference only, and to only include the ones you're changing
