### ISSUE TITLE
ACF Builder fails silently - Sage 10

### ISSUE THREAD

**Issue by fraserpage** [StoutLogic/acf-builder#170]
I'm using ACF Builder along with ACF Composer in Sage 10. When I do something ACF Builder doesn't like - say a syntax error - ACF Builder just fails silently without triggering a Symfony Exception. Is there something I need to do to get error reporting from ACF Builder? Help much appreciated. I love this tool.

**Comment by Log1x** [comment]
This is a question for the ACF Composer repo - but assuming you're on the latest Acorn v3 and you updated your bootloader in `functions.php`, you should have error reporting already.

**Comment by fraserpage** [comment]
Thanks very much for the reply @Log1x (and for all the work you do in the community!). I was on Acorn 2. After upgrading it I now get an exception, though it's just `Skipping provider [Log1x\AcfComposer\Providers\AcfComposerServiceProvider] because it encountered an error [Exception].` with no insight into what went wrong in ACF Composer. Is that expected?

**Comment by Log1x** [comment]
You should find the cause further down the error stack. Make sure you have [Ignition installed](https://roots.io/acorn/docs/error-handling/#ignition).

**Comment by fraserpage** [comment]
Thanks @Log1x. This is what I get if I do anything wrong in a FieldsBuilder object. Is that what you'd expect to see? I'd love to have a line or even file reference to help hunt down the error.

<img width="1391" alt="image" src="https://user-images.githubusercontent.com/10470769/226722134-84ff7935-9c94-4565-bba6-a8f45d412f1d.png">
