### ISSUE TITLE
Can not determine field key for repeater's collapsed value

### ISSUE THREAD

**Issue by joseph-farruggio** [StoutLogic/acf-builder#171]
I have a repeater `priority_ads` and I want the collapsed value to be the `ad_title` subfield's key. I'm having trouble determining the field's key. The field is added to the repeater using addFields().

I've tried multiple variations of field keys using these docs:
https://github.com/StoutLogic/acf-builder/wiki/generated-keys
https://github.com/StoutLogic/acf-builder/wiki/composing-fields#generated-keys

I get an error each time that the field (based on the key I provided) does not exist.

I've created a simplified version of my implementation:

``` php
<?php
use StoutLogic\AcfBuilder\FieldsBuilder;

/**
 * Subfield template
 */
$ad_set = new FieldsBuilder('ad_set');
$ad_set
    ->addTab('ad_content')
    ->addText('ad_title', ['wrapper' => ['width' => '50%']]);

/**
 * Field group with repeater
 */
$wp_custom_ads = new StoutLogic\AcfBuilder\FieldsBuilder('wp_custom_ads');
$wp_custom_ads
    ->addRepeater('priority_ads', ['layout' => 'block', 'button_label' => 'New Ad', 'collapsed' => 'FIELD_KEY_HERE'])
    ->addFields($ad_set)
    ->setLocation('options_page', '==', 'wp-custom-ads');

add_action('acf/init', function () use ($wp_custom_ads) {
    acf_add_local_field_group($wp_custom_ads->build());
});
```

**Comment by stevep** [comment]
Hey @joseph-farruggio I agree the docs probably aren't clear on this, but I tried your example using `ad_title` as the collapsed key and it worked for me. But maybe in your more complicated example there is another issue?

<img width="1673" alt="Screenshot 2023-03-29 at 9 52 10 AM" src="https://user-images.githubusercontent.com/9717/228580234-34de7cbe-e586-41a9-bb29-75ccfd28b215.png">


```php
/**
  * Subfield template
  */
$ad_set = new FieldsBuilder('ad_set');
$ad_set
  ->addTab('ad_content')
  ->addText('ad_title', ['wrapper' => ['width' => '50%']]);

/**
  * Field group with repeater
  */
$wp_custom_ads = new FieldsBuilder('wp_custom_ads');
$wp_custom_ads
  ->addRepeater(
    'priority_ads',
    ['layout' => 'block', 'button_label' => 'New Ad', 'collapsed' => 'ad_title']
  )
  ->addFields($ad_set)
  ->setLocation('options_page', '==', 'wp-custom-ads');

add_action('acf/init', function () use ($wp_custom_ads) {
    acf_add_local_field_group($wp_custom_ads->build());
});
```

**Comment by joseph-farruggio** [comment]
That works, thanks!

Based on the docs, I thought it had to be prepended with `field_`.
