### ISSUE TITLE
ACF Extended Compatible? 

### ISSUE THREAD

**Issue by louiswalch** [StoutLogic/acf-builder#173]
Hi, is this compatible with the additional options, configurations and fields in ACF Extended?
https://www.acf-extended.com/

**Comment by Log1x** [comment]
Yes. You will have to export JSON/PHP or code dive to find out what keys/fields are called, though. Most are prefixed with `acfe_`.

**Comment by EHLOVader** [comment]
I was wondering about this and if there was a place to find this in documentation or elsewhere. The best I could find was that their code seems to define defaults for each of their custom fields. 

https://github.com/search?q=repo%3Aacf-extended%2FACF-Extended++%24this-%3Edefaults&type=code&p=2

So you might be able to use this search result to find the settings keys and the custom field type name needed to configure the fields from ACF Builder directly.

**Comment by louiswalch** [comment]
I've just gone into native ACF, create the field and set ACF/ACFE settings, then export the field group as PHP. The output will give you all the options you need to place in your `->addWhatever` call for ACF Builder. It's a little annoying at first, but afterwards you can just copy/paste then for future uses. Really just a matter of figuring out what all the acfe settings are.

Once you get over that, ACF Builder is a awsome tool. Really saves a ton of the initial effort in getting a site set up.

For Example:
`
    ->addFlexibleContent('modules', [ 'label'=>'', 'button_label'=>'Add Content', 'acfe_flexible_stylised_button'=>1, 'acfe_flexible_layouts_thumbnails'=>1, 'acfe_flexible_remove_button'=>'duplicate', 'acfe_flexible_modal'=>[ 'acfe_flexible_modal_enabled'=>1, 'acfe_flexible_modal_title'=>'Add Content', 'acfe_flexible_modal_size'=>'large', 'acfe_flexible_modal_col'=>4, 'acfe_flexible_modal_categories'=>0 ] ])`

**Comment by TimAtTeamlemke** [comment]
If you're using [Log1x ACF-Composer](https://github.com/Log1x/acf-composer/blob/master/config/acf.php) you can also set acfe defaults for specific field types:
```
'fieldGroup' => ['instruction_placement' => 'acfe_instructions_tooltip'],
'repeater' => ['layout' => 'block', 'acfe_repeater_stylised_button' => 1, 'wpml_cf_preferences' => 1],
'group' => ['layout' => 'block', 'acfe_group_modal' => 0],
```

I also found a few available settings by searching on [GitHub](https://github.com/search?q=repo%3Aacf-extended%2FACF-Extended++%24field%5B%27acfe_&type=code)
I'm missing a developers documentation too
