### ISSUE TITLE
❤️ FAQ: difference between acf-builder and extended-acf

### ISSUE THREAD

**Issue by chrillep** [StoutLogic/acf-builder#176]
Just a friendly question whats the biggest difference between acf-builder and extended-acf

### refs
* https://github.com/vinkla/extended-acf
* https://github.com/Log1x/acf-composer
* https://github.com/vinkla/extended-acf/issues/126
* https://github.com/Log1x/acf-composer/issues/167

**Comment by Log1x** [comment]
The discussion at vinkla/extended-acf#126 should've hopefully cleared this up. :)
