### ISSUE TITLE
Updated to 1.2 and image fields stopped working

### ISSUE THREAD

**Issue by seafarer** [StoutLogic/acf-builder#24]
My image field variables are outputting image IDs instead of image objects now. Here is the code I am using. 

```
$hero = new FieldsBuilder('hero');
$hero
  ->addImage('hero_image')
  ->setLocation('post_type', '==', 'page')

add_action('acf/init', function() use ($hero) {
  acf_add_local_field_group($hero->build());
});

```

I also tried adding `'return_format' => 'array',` to the `addImage` arguments but it did not affect it.

Any thoughts?

**Comment by stevep** [comment]
Can you paste the output of the `build` function using `print_r`? Also what version of acf are you using?

**Comment by seafarer** [comment]
So I had to resave / update the posts and then everything started working. New fields also work fine.

**Comment by stevep** [comment]
I probably should have bumped the version to 2.0 instead of 1.2  It seems there was a breaking change I didn't account for because the keys changed. They had to in order to be properly function and be namespaced. Therefore ACF needed to be resave the key values in the DB. Sorry about that.
