### ISSUE TITLE
Conditional issue with addFields

### ISSUE THREAD

**Issue by convergingmatter** [StoutLogic/acf-builder#28]
I updated from an older version to get the recursive conditional fix #26 and now I get an error where ever I used addFields with a conditional.

`Uncaught exception 'Exception' with message 'No such function: conditional' in /Users/Removed/vendor/stoutlogic/acf-builder/src/ParentDelegationBuilder.php:69`

Tested with a very simple setup:
```
$fields = new FieldsBuilder('fields');
$fields
  ->addText('fields_text');

$builder = new FieldsBuilder('fields_conditional');
$builder
  ->addSelect('select')
    ->addChoice('hide')
    ->addChoice('show')
  ->addText('text')
  ->addFields($fields)
    ->conditional('select', '==', 'show')
 ->setLocation('post_type', '==', 'page');
```

By the way, love the builder, quick and easy to use.

**Comment by stevep** [comment]
So can you tell me a little about your intentions with this? Is it to add a conditional to an entire group of fields that would be in variable `$fields` or just the last field in `$fields`, which in this case would be `fields_text`?

The former I don't think ever worked and still won't work, but the latter might have worked.

In this [commit](https://github.com/StoutLogic/acf-builder/commit/61974e448c264b4e96f3a4eacc211459130aba3f?diff=unified#diff-3e36c4b56c548de93cd0391b8af4d9deL558) the `conditional` method was moved out of the `FieldsBuilder` class and into a newly created [`FieldBuilder` class](https://github.com/StoutLogic/acf-builder/commit/61974e448c264b4e96f3a4eacc211459130aba3f?diff=unified#diff-0061687a945612312c072ecb61c97adcR156)

And the old `conditional` method on the `FieldsBuilder` would have operated on the last field added to the FieldsBuilder instance. This will no longer work.

Instead I think you can use `getField` to get the `fields_text` field and add the conditional specifically to that filed in your `$builder` `FieldsBuilder` instance.

```php
$fields = new FieldsBuilder('fields');
$fields
  ->addText('fields_text');

$builder = new FieldsBuilder('fields_conditional');
$builder
  ->addSelect('select')
    ->addChoice('hide')
    ->addChoice('show')
  ->addText('text')
  ->addFields($fields)
  ->getField('fields_text') // <-- Operate on a specific field 
    ->conditional('select', '==', 'show')
 ->setLocation('post_type', '==', 'page');
```


Thanks for the kind words, glad people are finding value in this library.

**Comment by convergingmatter** [comment]
Yes, I wanted to add a conditional to an entire group of fields, but thanks to your response I see now that it was just blind luck that it worked.

I was pulling in only one field with addFields, so the conditional was operating on that field. I tested it by adding another field below it, making it the last field and that field was being operated on instead of the whole group, just like you said it would.

Since this is the intended way for this to work, I will upgrade to the current version and rework the code, thanks for your time.

**Comment by esquestudio** [comment]
Hello! I'm a bit unclear on the solution for this. Looking for a way, in the example below, in that the `header` and `text` fields will only be shown when the builder radio is set to `show`:
```
$fields = new FieldsBuilder('fields');
$fields
    ->addText('header')
    ->addTextArea('text')

$builder = new FieldsBuilder('builder');
$builder
    ->addRadio('select')
        ->addChoices('hide', 'show')
    ->addFields($fields['field_group'])
        ->conditional('select', '==', 'show')
```
Is this only possible by duplicating the fields, either by copy/paste or using `getField`, into the builder and then placing a conditional on them individually?

**Comment by stevep** [comment]
@esquestudio 

You shouldn't need to do: `->addFields($fields['field_group'])`

`->addFields($fields)` should work, does that solve the issue?

**Comment by esquestudio** [comment]
Sorry Steve, I was trying to create a simplified example and I had a typo there.
```
$fields['image_mask'] = new FieldsBuilder('image_mask');
$fields['image_mask']
    ->addField('image', 'focal_point')
    ->addRadio('mask')
        ->addChoices(['maskA' => 'Mask A'], ['maskB' => 'Mask B'], ['maskC' => 'Mask C'])

$fields['page_content'] = new FieldsBuilder('page_content');
$fields['page_content']
    ->addFlexibleContent('sections')
        ->addLayout('info_content')
            ->addRadio('style')
                ->addChoices('Headline', 'Image Mask', 'Background')
            ->addText('headline')
                ->conditional('style', '==', 'Headline')
            ->addFields($fields['image_mask'])
                ->conditional('style', '==', 'Image Mask')
            ->addImage('background')
                ->conditional('style', '==', 'Background')
```
That's basically what I've got. Without the conditional, the 'image_mask' fields are displayed just fine. When I add `->conditional('style', '==', 'Image Mask')` under `->addFields($fields['image_mask'])` I'm getting the error: `No such function: addLayout`. Any advice? Thanks for the quick response!

**Comment by stevep** [comment]
I assume you want both fields in the image_mask fields builder to be conditional on the style value. The above configuration does not achieve that. My suggestion would be use use an ACF group and apply the conditional to the group instead of the individual fields in the group.

```php
$fields['image_mask'] = new FieldsBuilder('image_mask');
$fields['image_mask']
    ->addField('image', 'focal_point')
    ->addRadio('mask')
        ->addChoices(['maskA' => 'Mask A'], ['maskB' => 'Mask B'], ['maskC' => 'Mask C']);

$fields['page_content'] = new FieldsBuilder('page_content');
$fields['page_content']
    ->addFlexibleContent('sections')
    ->addLayout('info_content')
        ->addRadio('style')
            ->addChoices('Headline', 'Image Mask', 'Background')
        ->addText('headline')
            ->conditional('style', '==', 'Headline')
        ->addGroup('image_mask')
            ->conditional('style', '==', 'Image Mask')
            ->addFields($fields['image_mask'])
            ->endGroup()
        ->addImage('background')
            ->conditional('style', '==', 'Background');
```

**Comment by esquestudio** [comment]
That did it! Group was the answer. Thanks so much.
