### ISSUE TITLE
Shorthand for adding multiple choices via arrays

### ISSUE THREAD

**Issue by christianmagill** [StoutLogic/acf-builder#33]
I think the documentation should be clearer as for adding multiple choices via [key => value] arrays.

https://github.com/StoutLogic/acf-builder/wiki/choices#shorthand-for-adding-multiple-choices

It's not clear which is the "label" and which is the field "value", and as it turns out the field "value" should be the key and the field "label" should be the value which can be confusing.

I also think it would be great to support adding multiple entries in a single associative array. Currently this causes issues where the values are used as both the keys and the values in the output array.

**Comment by stevep** [comment]
@christianmagill ya that one was bad, I had to look it up in the code to even know. 

It indeed is `['choice' => 'label']` which I'm not in love with.

**Comment by christianmagill** [comment]
@stevep, I think this still needs to be addressed.

Especially dealing with multiple choices in a single array.

If you use this example from docs, and update the labels on to start with uppercase, the values end up being uppercase too.

```
 'fields' => [
    [
        ...
        'name' => 'background_color',
        'type' => 'radio',
        'choices' => [
            'red' => 'Red',
            'blue' => 'Blue',
            'green' => 'Green',
        ],
        'default_value' => 'blue',
    ],
],
```

**Comment by stevep** [comment]
Yeah the library kinda mirrors what acf does, where the key is the value and the value is the label. Perhaps by default, the `addChoice` method should automatically capitalize the label.

**Comment by Log1x** [comment]
After a lot of extended use I agree the value should capitalize the label by default.

**Comment by christianmagill** [comment]
It seems the value is also getting uppercased or at least it is getting copied from the label. I can have an uppercased label and a lowercased value and the label will display as uppercased and the value will return as uppercased as well.
