### ISSUE TITLE
required, instructions, and defaultValue methods are mis-documented

### ISSUE THREAD

**Issue by burning-brush** [StoutLogic/acf-builder#36]
Wiki documentation shows these methods as `required()`, `instructions()`, and `defaultValue()`, but should be `setRequired()`, `setInstructions()`,  and `setDefaultValue()`.

Otherwise they throw an exception of "No method exists."

The prefix 'set' is more inline with the `setConfiguration()` method but `conditional()` has no prefix and I'm all for less typing where ever possible so I vote for some wrapper methods of some kind.

**Comment by stevep** [comment]
Thanks for catching that. Fixed them in the wiki. Sorry for taking so long to respond
