### ISSUE TITLE
Radio field "defaultValue" method is not found.

### ISSUE THREAD

**Issue by christianmagill** [StoutLogic/acf-builder#41]
I'm trying to add a radio field and running into an issue with the defaultValue method.

```
->addRadio('project_thumbnail_extend', ['label' => 'Extend Thumbnail'])
   ->addChoice('none', 'None')
   ->addChoice('left', 'Left')
   ->addChoice('right', 'Right')
   ->defaultValue('none')
```

`( ! ) Fatal error: Uncaught Exception: No such function: defaultValue in /Users/christianmagill/Code/Sites/influencedesign/web/app/themes/influencedesign/vendor/stoutlogic/acf-builder/src/ParentDelegationBuilder.php on line 69`

**Comment by christianmagill** [comment]
Ah.. seems to be a leftover reference from 

https://github.com/StoutLogic/acf-builder/issues/36

https://github.com/StoutLogic/acf-builder/wiki/choices

**Comment by stevep** [comment]
Thanks for catching that @christianmagill !
