### ISSUE TITLE
Post object field doesn't find posts that do exist

### ISSUE THREAD

**Issue by zimdin12** [StoutLogic/acf-builder#43]
after I created Post Object field with acf-builder, post object field didn't find any results (but posts did exist, but ajax returned results as false) .. That problem is related to PHP because it didn't occur after I switched to PHP 7.1 (from 7.0)
acf-builder v1.4.0
acf-pro v5.5.14

NB: I used custom post type.

**Comment by stevep** [comment]
@zimdin12 Can you provide code samples for the field group and custom post type registration? Thanks.

**Comment by zimdin12** [comment]
That code was scattered in different classes and surrounded by not relevant code, so I thew these together into one function for better screenshot..
![registerfields](https://user-images.githubusercontent.com/18162148/29358516-fe46b930-8283-11e7-99a8-33bac9651e88.JPG)

I am using "jjgrainger/PostTypes": v1.1.2 for creating post types.. 
![registerposttype](https://user-images.githubusercontent.com/18162148/29358517-fe6069fc-8283-11e7-8b4a-b8f919feed3d.JPG)

**Comment by stevep** [comment]
Would it be possible to paste in the php array output when you print_r() the return array from the ->build() call?

When it broke what was upgraded? The ACF builder version? Did it work in the previous version? Or just broke php 7 -> 7.1?

Also does upgrading to acf 5.6.1 help?

**Comment by zimdin12** [comment]
I am sorry but I cant test it anymore.. Upgrading to PHP 7.1 fixed that problem for me, but it would be nice if it would work well with PHP 7 or PHP 5.6

**Comment by DalkMania** [comment]
This seems to be an issue still. 

`function codex_custom_init()
{
    $args = [
        'public' => true,
        'label' => 'Books'
    ];
    register_post_type('book', $args);
}
add_action('init', 'codex_custom_init', 0);

add_action('acf/init', function () {
    $acf = new StoutLogic\AcfBuilder\FieldsBuilder('sparse-content', [
        'key' => 'sparse-content',
        'title' => 'Sparse Content'
    ]);
    $acf->addPostObject('related_books', ['post_type' => 'book']);
    $acf->setLocation('post_type', '==', 'page');
    acf_add_local_field_group($acf->build());
});`

I tried the code above with no luck. Books do exist. But the dropdown in the admin is empty. Am I missing something ? 

Thanks
