### ISSUE TITLE
Add Range Field

### ISSUE THREAD

**Issue by Log1x** [StoutLogic/acf-builder#44]
[ACF v5.6.2](https://www.advancedcustomfields.com/blog/acf-pro-5-6-2-update/) was released today with the addition of a new [Range](https://www.advancedcustomfields.com/resources/range/) field.

`->addRange()`? 💓 

Thanks a lot in advance. ACF Builder makes me very happy.

**Comment by stevep** [comment]
@Log1x for sure. I probably won't be able to add it until next week sometime. As a reminder you can still use it (or any field type, including 3rd party plugins) if you call `addField`.

```php
$builder = new FieldsGroupBuilder('my_group');
$builder->addField('my_range', 'range', []);
```

It looks to have the similar options as number according to the source code.
```php
$this->name = 'range';
$this->label = __("Range",'acf');
$this->defaults = array(
    'default_value'	=> '',
    'min'			=> '',
    'max'			=> '',
    'step'			=> '',
    'prepend'		=> '',
    'append'		=> ''
);
```

**Comment by stevep** [comment]
Added in 1.5.0
