### ISSUE TITLE
Modifying (appending/removing) fields of an existing group field

### ISSUE THREAD

**Issue by kaisermann** [StoutLogic/acf-builder#45]
Is it possible to modify/append/remove fields of an existing group field with the `->modifyField()`? 

I'm trying to wrapping my head around it, but I just can't figure it out.

**Comment by stevep** [comment]
Take a look at this page in the wiki about [Modifying Fields](https://github.com/StoutLogic/acf-builder/wiki/modifying-fields) Does it help?

**Comment by kaisermann** [comment]
I read it before posting the issue! 

What I'm trying to do is something like: 

```php
$page_fields = new FieldsBuilder('page');
$page_fields
    ->addGroup('page', [
            'label' => 'Configurações da página',
            'wrapper' => [ 'width' => '100%' ]
        ])
        ->addImage('image_id', [
            'label' => 'Imagem de topo',
            'return_format' => 'id',
        ])
    ->endGroup();

// In another file...
$page_fields->modifyField('page', function($fieldsBuilder) {
    return $fieldsBuilder->addText('appended_field');
});
```

But I'm getting the following error: 

```
Fatal error: Uncaught StoutLogic\AcfBuilder\ModifyFieldReturnTypeException: Function "modifyField" closure argument is expected to return a StoutLogic\AcfBuilder\FieldsBuilder, object returned instead. 
```

Obs: if I copy the code sample from the wiki page, I get an error saying 'setConfig' doesn't exist.

**Comment by stevep** [comment]
Perfect thanks this helps. I hope to look into it soon. Looks like a test case isn't catching this.

**Comment by Log1x** [comment]
Not sure if related but if I close `->addGroup();` when adding fields to it the group ends without an `->endGroup()`.

Example from a personal project:

```
if (!empty($overviews)) {
	$review->addGroup('overview_group', ['layout' => 'row']);
    foreach ($overviews as $overview) {
        $key = sanitize_title_with_underscores($overview['title']);
        $review->addText('overview_'.$key, ['label' => $overview['title'], 'wrapper' => $this->settings['wrapper']])
            ->setInstructions($overview['description']);
    }
	$review->endGroup();
}
```

I dynamically add fields to my reviews based on the niche (term) they are in for a review overview, but my above code doesn't work because the `->addGroup()` ends the second its closed.

**Comment by kaisermann** [comment]
I also thought about dynamically adding the fields before posting here, but with the current way I'm using `acf-builder` it would become ugly as sh**...  

Btw, pretty admin there @Log1x !

**Comment by stevep** [comment]
@Log1x  I think you need to capture the group in a variable and then add the fields to that.
`addGroup` will return the GroupBuilder instance. `endGroup` will no be needed, only if you did once continuous method chain and needed to traverse back up to the parent FieldsBuilder instance. 

Try:
```php
if (!empty($overviews)) {
    $group = $review->addGroup('overview_group', ['layout' => 'row']);
    foreach ($overviews as $overview) {
        $key = sanitize_title_with_underscores($overview['title']);
        $group
            ->addText('overview_'.$key, [
                'label' => $overview['title'],
                'wrapper' => $this->settings['wrapper']
            ])
            ->setInstructions($overview['description']);
    }
}
```

**Comment by Log1x** [comment]
Thanks @stevep -- that did the trick.

@kaisermann thanks :) truth be told, it's extended onto Selene's WordPress styles-- so thank you.

![Screenshot](https://log1x.com/screenshots/2017-09-13_18-34-35_BILd5.png)

**Comment by kaisermann** [comment]
@stevep Thanks, that can be used in my case as well!

@Log1x Oh boy, I wasn't expecting that 😮  (I moved a updated version to [another repo](https://github.com/kaisermann/WPDLS) if you wanna know)

**Comment by stevep** [comment]
@kaisermann Nice though I do think that might be a short term solution. The last version that added groups may have broken this code. Adding a field before used to return a `FieldsBuilder` (plural), but now it returns the actual `FieldBuilder` (singular) of the field you just added, but the closure you pass to `modifyField` is still expected to return a `FieldsBuilder` (plural). 

The tests should have caught this but they didn't. I still need to fix this I think, so I will leave this issue open for now, but I'm glad you don't have to wait on my to proceed.

**Comment by stevep** [comment]
Ended keeping the requirement of the closure passed to `modifyField` to return the `FieldsBuilder` object and updated the [documentation](https://github.com/StoutLogic/acf-builder/wiki/modifying-fields#insert-fields-after-a-particular-field) to reflect this.
