### ISSUE TITLE
Fields arguments docs

### ISSUE THREAD

**Issue by kaisermann** [StoutLogic/acf-builder#47]
I'm currently using [this article](https://bwap.ch/guide-to-registering-acf-fields-via-php) to know which arguments a certain field accepts. 

Maybe it would be good to have it's content on the `wiki` or something alike (I'm reluctant to depend on an external link that can go off anytime...).

Edit: The [official ACF "guide"](https://www.advancedcustomfields.com/resources/register-fields-via-php/) is missing a lot of info.

**Comment by stevep** [comment]
I agree, this would be good to have. Best case is if ACF did it themselves, but alas. I wish github made it easy to allow merge requests with the wiki. I found this link which tries to sync a separate repo for the wiki with the actual wiki on this repo. http://www.growingwiththeweb.com/2016/07/enabling-pull-requests-on-github-wikis.html

I might try to do that later this week. That way everyone can easily contribute to it.

**Comment by stevep** [comment]
I set up repo syncing via travis so any merges to master on the wiki repo will get merged into the actual wiki under this project. I'm moving this issue [over there](https://github.com/StoutLogic/acf-builder-wiki/issues/1).
