### ISSUE TITLE
Using addRepeater and Conditional together

### ISSUE THREAD

**Issue by tdwesten** [StoutLogic/acf-builder#49]
Hi we want to add conditional logic to a repeater, but how? Here the code of our try; 

`
$field_group_title = ‘Diensten inhoudsopgave’;
        $footer_settings   = new FieldsBuilder( sanitize_title_with_dashes( $field_group_title ) );

        $footer_settings
            ->setGroupConfig( ‘title’, $field_group_title )
            ->addRadio( ‘toc_type’, [
                ‘label’   => ‘Type inhoudsopgave’,
                ‘layout’  => ‘vertical’,
                ‘return_format’ => ‘array’
            ] )
            ->addChoices([
                ‘page_scroll’ => ‘Links binnen de pagina’,
                ‘page_links’  => ‘Links naar andere pagina’s’,
            ] )
            ->addRepeater(‘page_links’)
                ->addText(‘title’)
                ->addPostObject(‘page_id’, [
                    ‘label’=> ‘Pagina’,
                    ‘post_type’ => ‘page’,
                    ‘return_format’ => ‘id’,

                ])
            ->endRepeater()
            ->addText(‘title’)
            ->conditional( ‘toc_type’, ‘==‘, ‘page_links’)
            ->setLocation( ‘page_template’, ‘==‘, ‘template-services.php’ );
`

**Comment by stevep** [comment]
@tdwesten I believe the issue you have is in the `addChoices` call. [See the documentation for shorthand `key => value` choices](https://github.com/StoutLogic/acf-builder/wiki/choices#shorthand-for-adding-multiple-choices)

It should be:
```php
->addChoices(
    ['page_scroll' => 'Links binnen de pagina'],
    ['page_links'  => 'Links naar andere pagina’s'],
)
```

With each `key => value` choice in its own array. It is done this way so you could pass non key-value choices in the function call as well, as the documentation shows. Hopefully this fixes it.

**Comment by tdwesten** [comment]
Thanks! That was the fix!
