### ISSUE TITLE
Conditionals don't work when checking value of a parent field.

### ISSUE THREAD

**Issue by stevep** [StoutLogic/acf-builder#52]
When trying to add a conditional from a field in a Flexible Layout which depends on the value of a field that is a sibling to the Flexible Content field, it fails with a `FieldNotFoundException`. 

## Example:

A slider where normally only the background changes and the content stays fixed. But the option can be set that each slide has its own content.

```php
$builder = new FieldsBuilder('slider');
$slider
    ->addTrueFalse('enable_slide_content')
            ->setInstructions('By default only the background will change on the slider, while the content of the first slide will remain. If you want the content to change with each slide, enable this option.')
    ->addWysiwyg('slider_content')
        ->conditional('enable_slide_content', '!=', '1')
    ->addFlexibleContent('slides')
         ->addLayout('slide')
              ->addImage('background')
              ->addWysiwyg('content')
                   ->conditional('enable_slide_content', '==', '1');
$builder->build()
```

We will get a `FieldNotFoundException` due to `enable_slide_content` not being found in the slide layout. But this is valid ACF.

## Solution:

When a field isn't found, we need to traverse up the builder tree and check for the field name at each ancestor builder before throwing the exception.  That is the easy part.

The hard part is doing the same in the NamespaceFieldKey transformation. Because we want the namespaced key to be that of the ancestor field, not the child field.

Potentially a hard bug to fix, might require significant rewrite. But would be a really useful feature.

**Comment by Log1x** [comment]
I have ran into this issue as well when attempting to use a `TrueFalse` for `Columns Enabled?` and then wanting to have the column sizes inside of the `FlexibleContent` `Layout`'s with `conditional('columns_enabled', '==', true)`.

Since I wasn't able to obtain the value of `columns_enabled` inside of my Flex Field, I simply have to have the partially-useless column select boxes there even if columns are disabled on the section. :(

**Comment by JeffAspen** [comment]
@Log1x @stevep Did you find a solution for this? I'm having the same issue with a repeaters. If I have a select field outside a repeater and my condition inside the repeater, I get an error.

`->addSelect('variation')
        ->addChoice('var1', 'Variation 1')
        ->addChoice('var2', 'Variation 2')
      
        ->addRepeater('slide', [
        'min' => 1,
        'max' => 7,
        'button_label' => 'Add Slide',
        'layout' => 'block',
      ])
      
        ->addSelect('card_border_location')
          ->addChoice('top', 'Top')
          ->addChoice('bottom', 'Bottom')
          ->conditional('variation', '==',   'var1')  
        
          ->addText('some_text')
      
        ->endRepeater() `

**Comment by stevep** [comment]
@JeffAspen There is no solution yet unfortunately, it has to do with how field keys get namespaced internally.

**Comment by camtheperson** [comment]
@Log1x @stevep Still no solution here?

**Comment by stevep** [comment]
@camtheperson @Log1x  I've actually been working on this today, will push soon to the develop branch for testing

**Comment by mmoollllee** [comment]
Is this already implemented? I'd love to test this as I have this problem right now.

**Comment by faahim** [comment]
Facing this issue with repeater field. Trying to use a fields value for conditional that resides outside of my repeater. Feels like a pretty common use-case? Would love to see this in production release! 🙂

**Comment by stevep** [comment]
@mmoollllee @faahim There is code on the dev branch that might work. I started it earlier this year and the a couple tests I wrote pass when run locally, but I haven't really used it in production. Would you be able to install the develop branch version of ACFBuilder via composer and see if it works and doesn't break anything on your end? 

Changes and commit: https://github.com/StoutLogic/acf-builder/commit/6287f89b897b73525fefb7b8923693fb2c02d957

In your composer.json change it to:
`"stoutlogic/acf-builder": "dev-develop"` and then run `composer update`

The idea is that you can either [refer to a the parent field name directly in the child conditional](https://github.com/StoutLogic/acf-builder/commit/6287f89b897b73525fefb7b8923693fb2c02d957#diff-a1b4c3472dff5751fc0ed114f03f67c03f8d817d38236b7f51d4773efb5cb0f1R182-R193), or [create a custom key](https://github.com/StoutLogic/acf-builder/commit/6287f89b897b73525fefb7b8923693fb2c02d957#diff-a1b4c3472dff5751fc0ed114f03f67c03f8d817d38236b7f51d4773efb5cb0f1R119-R133) and refer to that in a child conditional.

**Comment by intelligence** [comment]
Can confirm that this works great:
```
->addTrueFalse('use_images', [
    'label' => 'Use images in cards?',
    'default_value' => 1,
    'ui' => 1,
])
->addRepeater('cards', [
    'min' => 1,
    'layout' => 'block',
    'button_label' => 'Add Card',
])
    ->addWysiwyg('content', [
        'toolbar' => 'full',
        'media_upload' => 0,
    ])
    ->addImage('image', [
        'required' => 1,
    ])
        ->conditional('use_images', '==', '1')
->endRepeater();
```

**Comment by stevep** [comment]
@intelligence Awesome, I used it on a project of mine as well and it worked to. I didn't notice any issues. I will try to get it in an official release this or next week.

You didn't notice any slow down or anything did you?

**Comment by maluueu** [comment]
> @intelligence Awesome, I used it on a project of mine as well and it worked too. I didn't notice any issues. I will try to get it in an official release this or next week.
> 
> You didn't notice any slow down or anything did you?

I tried it and for me it always throws the field key not found exceptions.. 
Any ideas?

Thank you for this awesome library.

**Comment by maluueu** [comment]
For anybody that cant get this to work this is what is working for me currently as a workaround for fields where you need to access a parent field in the condition. 

**Use the default **acf load** filter like this:**

`add_filter( 'acf/load_field/name=field_name', 'add_condition'  , 10);
`
```
public function add_condition($field) {

$field['conditional_logic'] =  array(
				array(
					array(
						'field' => 'field_5fe7a9bcfb9e0',
						'operator' => '==',
						'value' => '1',
					),
				),
			);
return $field;
}
```

Like this you can specify any conditions you want without breaking stuff because AcfBuilder has already generated the fields at the point where the hook run.

**Comment by Malin88** [comment]
Conditional doesn`t work inside addGroup :/

**Comment by pjho** [comment]
I've encountered this issue using `addGroup` as well. Switching to dev branch resolves it. Is this fix likely to end up in a release any time soon or is it too untested? What could be done to help get it in?

Thanks for your work on this library. It really is nice to work with and is the main missing feature for ACF. So nice work! 👍

**Comment by stevep** [comment]
@pjho I was kinda waiting to see how people reported back with the develop branch, but if people aren't running into any issues, I can release it as 1.11 

Thanks for the kind words, I'm glad so many others are able to find it useful.

**Comment by stevep** [comment]
Fixed in https://github.com/StoutLogic/acf-builder/releases/tag/1.11.0
