### ISSUE TITLE
Hide on screen

### ISSUE THREAD

**Issue by broskees** [StoutLogic/acf-builder#54]
I can't find any documentation on this, how do I use the 'Hide on Screen' ACF functionality.
```
$banner = new StoutLogic\AcfBuilder\FieldsBuilder('banner', [
    'title' => 'Banner',
    'style' => 'seemless',
    'hide_on_screen' => [
        'content_editor',
        'permalink'
    ]
]);
```

Is there a quick option similar to toggle all?

**Comment by stevep** [comment]
What you have should work, does it not?
Are you asking to toggle all the hide_on_screen features or to hide on all groups, or just a short cut?

While not built in (not saying it shouldn't be) but you could write a helper function like:

```php
function hideOnScreen($builder, $value)
{
    $hideOnScreen = $builder->getGroupConfig('hide_on_screen') ?: [];
    $hideOnScreen[] = $value;

    return $builder->setGroupConfig('hide_on_screen', $hideOnScreen);
}

$banner = hideOnScreen($banner, 'content_editor');
```

**Comment by Tailzip** [comment]
Not sure if you're still having the issue @broskees  but `content_editor` should be `the_content`.

Here's the list of options values grabbed from HTML markup: 
- Permalink -> `permalink`
- Content Editor -> `the_content`
- Excerpt -> `excerpt`
- Custom Fields -> `custom_fields`
- Discussion -> `discussion`
- Comments -> `comments`
- Revisions -> `revisions`
- Slug -> `slug`
- Author -> `author`
- Format -> `format`
- Page Attributes -> `page_attributes`
- Featured Image -> `featured_image`
- Categories -> `categories`
- Tags -> `tags`
- Send Trackbacks -> `send-trackbacks`

**Comment by Dynamo6** [comment]
The method above doesnt seem to work for the new block editor layout in WP v5. Does anyone know how to fix this? Cheers

**Comment by tallcoder** [comment]
Any updates here? I'm using this within a plugin and I cannot get rid of the content editor.

**Comment by Log1x** [comment]
This is not an ACF Builder related issue.

See: https://github.com/AdvancedCustomFields/acf/issues/112

Unless you're using Classic Editor – it is not as straight forward to rip out Gutenberg. It is currently not an option in ACF with `hide_on_screen`.
