### ISSUE TITLE
Massive DB conflicts

### ISSUE THREAD

**Issue by E-VANCE** [StoutLogic/acf-builder#56]
Hi there,

just got started using the `acf-builder` and very much appreciate the library!

I ran into an issue and I suspect a bug of some sorts with acf-builder to be responsible:

I register a number of different groups / fields and they somehow overlap in the DB. Different entries are merged into one although the field names are unique and I cannot wrap my head around it. Everything seems to be set up fine...?

## Example

The value I enter in the backend for `acf[field_basic_cta_title]` (save / refresh post) is being overwritten by the entry in `acf[field_home_about_title]`!

Meaning I cannot set the *about title* at all and it just keeps ignoring what I enter into the field...

## Steps I took

- Renamed the field groups
- Renamed the fields so the names wouldn't match any more (f.ex. `addText('about_title')` – this is obviously not needed though since the fields are unique due to their group-labels...)
- Deleted the post & created a new post
- Tried registering the fields without the builder-array, e.g. each field gets its own `acf_add_local_field_group` since that *could* interfere somehow

Nothing changes, still seeing the errors...

## Code

**Field group A**

    /**
     * BASIC -- CTA / Call to action
     */
    $basic_cta = new FieldsBuilder('basic_cta');
    $basic_cta
      ->addText('title')
      ->addText('subtitle')
      ->addText('button_label')
      ->addUrl('button_target')
      ->addRadio('style')
        ->addChoices('light', 'dark', 'white')
        ->setDefaultValue('light')
      ->addRadio('positon')
        ->addChoices(['float' => 'Nebeneinander'], ['break' => 'Untereinander'])
        ->setDefaultValue('float')
      ->setLocation('post_type', '==', 'page');

**Field group B**

    /**
     * HOME -- About-Section
     */
    $home_about = new FieldsBuilder('home_about');
    $home_about
      ->addImage('image')
      ->addText('title')
      ->addWysiwyg('text')
        ->setConfig('delay', 1)
      ->setGroupConfig('order_no', 4)
      ->setLocation('page_type', '==', 'front_page');

**Builder**

    /**
     * BUILD -- Now we create / register the fields
     * The array should really build automatically, room for improvement here...
     */

    $acf_fields = [
      $basic_cta,
      [...]
      $home_about,
      [...]
    ];

    add_action('acf/init', function() use ($acf_fields) {
      foreach ($acf_fields as $acf_field) {
        if ($acf_field instanceof FieldsBuilder) {
          acf_add_local_field_group($acf_field->build());
        }
      }
    });

What I can try to further debug this? Any idea what might be causing these problems?

Any help is greatly appreciated!

Thanks & regards,
Henning

P.S.: I use [ACF Fluent](https://github.com/samrap/acf-fluent) to retrieve / display the fields but to rule that stuff out I tested with direct calls via `the_field('field_home_about_title')` but to no avail...

**Comment by E-VANCE** [comment]
Just to emphasize: The fields even are **in sync**, e.g. when I change the value in `acf[field_home_about_title]` then `acf[field_basic_cta_title]` follows the change and updates.

Btw: Not related to #55, just removed the `addChoices`-stuff since maybe that caused the fields to break...

**Comment by stevep** [comment]
@E-VANCE So ACF Builder works just like normal ACF does in this instance. If you were to create two different field groups, both with a field named "title" and you set the location of both the same object (in this case the home page is where they would overlap), you should get the same overlapping. This is because how ACF stores fields in the post_meta table. The meta_key is title in both cases.

My advice would be to rename one of the title fields, perhaps home_about section's title since it will be less painful to upgrade across your code.

**Comment by E-VANCE** [comment]
Thanks for getting back and clarifying.

I can confirm that things are working if I make use of a more specific naming convention – I thought the group field would render the fields unique...

Thanks!!
