### ISSUE TITLE
Mutability / Updating fields when using addFields

### ISSUE THREAD

**Issue by E-VANCE** [StoutLogic/acf-builder#57]
Hi there,

I am having trouble updating fields when using the `addFields`-functionality – my fields disappear when editing the original FieldsBuilder.

Following the [wiki entry on composing fields](https://github.com/StoutLogic/acf-builder/wiki/composing-fields) I assumed that I *could* modify the original fields but that wouldn't have any effect on the master field(s)...

> When adding a FieldsBuilder to another FieldsBuilder with addFields or addLayout, that FieldsBuilder is cloned, which will lock in the fields and configs. So updating those fields at a later time on the original FieldsBuilder will not have an effect on the cloned versions. These cloned copies embedded in other FieldsBuilder can still be updated separately, so they are still mutable.

...but wouldn't destroy / hide them?

This is my setup (exemplary):

    /**
     * HOME -- Slider
     */
    $home_slider = new FieldsBuilder('home_slider');
    $home_slider
      ->addRepeater('slider', ['min' => 1, 'max' => 5, 'layout' => 'table'])
        ->addImage('image')
        ->addText('title', [
          'wp-typography' => 'content'
        ])
        ->addWysiwyg('text', [
          'wp-typography' => 'content'
        ])
        ->endRepeater()
      ->addText('claim');

    /**
     * HOME MASTER -- All home fields tabbed together
     */
    $home = new FieldsBuilder('home');
    $home
      ->addTab('Slider')
        ->addFields($home_slider)
      ->addTab('CTA Icons')
        ->addFields($home_cta_icons)
      ->setLocation('page_type', '==', 'front_page');

- Does it make sense that the whole `home`-section / -fields disappears when I modify any of included fields (f.ex. removing and/or adding a field to `home_slider` after initially registering the `home`-field)?
- How would I go about correctly to update the master field? Any way of forcing an update on the field logic? I tried removing it from `acf_add_local_field_group` and re-initiating but to no avail...

Sorry but either I haven't grasped the concept well enough (high probability) or this is a bug maybe?

Thanks for your insights.

Regards,
Henning

**Comment by stevep** [comment]
@E-VANCE can I see the code where you're doing the build?

I've tested building both basic and home on my site and both are showing up on my home/ front page

```php
add_action('acf/init', function() use ($home, $basic) {
    acf_add_local_field_group($home->build());
    acf_add_local_field_group($basic->build());
});
```

**Comment by E-VANCE** [comment]
Sure:


    /**
     * BUILD -- Now we create / register the fields
     * The array could build automatically, room for improvement here...?
     */

    $acf_fields = [
      $options_footer,
      $options_zitate,
      $basic,
      $home,
      $team_partial_single,
      $team_people,
      $about_verein,
      $faq,
      $pressemitteilungen,
      $pressedownloads,
      $zitate
    ];

    add_action('acf/init', function() use ($acf_fields) {
      foreach ($acf_fields as $acf_field) {
        if ($acf_field instanceof FieldsBuilder) {
          acf_add_local_field_group($acf_field->build());
        }
      }
    });

I just tried to also build with the 'children' (e.g. `$home_slider`, `$home_cta_icons` , `$home_stats` etc.) before using the `$home`-master but no change.

The field group still isn't being displayed on the home page...

Tried renaming the variable(s) like follows but also no change.

`$home_group = new FieldsBuilder('home_group');`

**Comment by stevep** [comment]
If you change the location of the home builder to all pages, do you see it then? At this point I would try to use isolation to debug. Since I was able to have it work locally, I don't think it is a bug per se.

```php
/**
 * HOME MASTER -- All home fields tabbed together
 */
$home = new FieldsBuilder('home');
$home
    ->addTab('Slider')
    ->addFields($home_slider)
    ->addTab('CTA Icons')
    ->addFields($home_cta_icons)
    ->addTab('Stats')
    ->addFields($home_stats)
    ->addTab('About')
    ->addFields($home_about)
    ->addTab('Videos')
    ->addFields($home_videos)
    ->addTab('Logos')
    ->addFields($home_logos)
    ->setLocation('post_type', '==', 'page');
```


Here are basic and home showing up on the home page of a local install:

<img width="1620" alt="screen shot 2018-04-17 at 12 02 04 pm" src="https://user-images.githubusercontent.com/9717/38885047-2e9f9980-4237-11e8-9d67-06fbaac9b18f.png">
<img width="1620" alt="screen shot 2018-04-17 at 12 00 54 pm" src="https://user-images.githubusercontent.com/9717/38885024-196ed7b0-4237-11e8-8c10-dee4c2224f34.png">

**Comment by E-VANCE** [comment]
> If you change the location of the home builder to all pages, do you see it then?

Changing the conditional to `->setLocation('post_type', '==', 'page')` solves it...!

Super weird, the directive `->setLocation('page_type', '==', 'front_page')` was working fine all the time before, now it just doesn't recognize my fields e.g. the stay hidden and aren't initiated. I can go back and forth and the issue remains...

Probably has to do with ACF directly...? Anyways, sorry to have bothered but this is one nasty bug I couldn't wrap my head around.

Using the ID of the front page (`->setLocation('page', '==', 2)`) now, that solves it.

Thanks for your testing & efforts, much appreciated!

Regards,
Henning
