### ISSUE TITLE
->addLayout should have attributes 

### ISSUE THREAD

**Issue by jornhenkes** [StoutLogic/acf-builder#58]
I am building an import script where I can convert acf-json files to AcfGroups. Now I'm running into an issue with the addLayout field. In my original json file a Layout has a `key`, `name`, `label` and `display`. In the AcfGroups a layout can only have a `name`. Since the label of the layout is a translated string of the name it would be great when the label can still be applied to the field. 

In the original json the Layout is described this way: 
```javascript
"layouts": [
                {
                    "key": "58fdc17c7498b",
                    "name": "page_anchor",
                    "label": "Verwijzing naar onderdeel",
                    "display": "block",
                    "sub_fields": [
                    ]
                }
]
```

My AcfGroup after converting is like this:
```php
->addLayout( 'images_multiple', [
                'key' => "58e4ad59b4665",
                'label' => "Meerdere afbeeldingen",
                'display' => "block",
            ] )
```

The `label` doesn't show in the view anymore. 

Is there a way to fix this?

**Comment by stevep** [comment]
@jornhenkes This is fixed in dev-master now. Until a new release is pushed (hopefully soon) you can use `"title": "Verwijzing naar onderdeel",` Basically before title was overwriting label.

**Comment by jornhenkes** [comment]
@stevep Thanks for fixing this! I found the title overwrite as well a couple of days ago, but this fix is great for when I convert the acf json to AcfBuilder.
