### ISSUE TITLE
Button Group Field

### ISSUE THREAD

**Issue by Log1x** [StoutLogic/acf-builder#65]
Hey Stout.

Was curious if [Button Group](https://www.advancedcustomfields.com/resources/button-group/) accidentally went overlooked? Checked the source and don't see it anywhere. I think it can be built off of `->addChoiceField`.

Also, for contributing in cases like this, do you have anything to follow? Is it as simple as writing the quick test and adding it to `FieldsBuilder.php`? Anywhere else it needs to be referenced?

**Comment by stevep** [comment]
@Log1x yes I had forgotten about it. It can be modeled after [addRadio](https://github.com/StoutLogic/acf-builder/blob/master/tests/FieldsBuilderTest.php#L332-L355), perhaps name it `addButtonGroup`

Make sure to add a test that models the [testAddRadio](https://github.com/StoutLogic/acf-builder/blob/master/tests/FieldsBuilderTest.php#L332-L355) in the FieldsBuilderTest class, you can just add it to the end.

I think that is all you need to do, (other than maybe test it locally in a WordPress install), then open a pull request, and if the TravisCI tests pass, we'll merge it in. Thanks a bunch!
