### ISSUE TITLE
Anyway to add fields to a Theme Options Page?

### ISSUE THREAD

**Issue by christianstclair** [StoutLogic/acf-builder#74]
Wondering if anyone has tried to use the builder and add fields to an options page https://www.advancedcustomfields.com/resources/options-page/

**Comment by Log1x** [comment]
Initialize the options page with `acf_add_options_page()` and set the location to the menu slug.

Example:

```
use StoutLogic\AcfBuilder\FieldsBuilder,

acf_add_options_page([
    'page_title' => get_bloginfo('name') . ' Theme Options',
    'menu_title' => 'Theme Options',
    'menu_slug'  => 'theme-options',
    'capability' => 'edit_theme_options',
    'position'   => '999',
    'autoload'   => true
]);

$options = new FieldsBuilder('theme_options',);

$options
    ->setLocation('options_page', '==', 'theme-options');
```

**Comment by christianstclair** [comment]
@Log1x Thanks!

**Comment by josialoos** [comment]
Hey, what if I want to add options subpages. I know how to register them, but how can I add fields to an options subpage?

**Comment by bassaroff** [comment]
I have a problem with several acf-options subpages.
When I try to add fields to the first parameters page, the fields on the second are deleted, and vice versa
`acf_add_options_sub_page(array(
        'page_title' 	=> 'Настройки шапки сайта',
        'menu_title'	=> 'Шапка',
        'parent_slug'	=> 'theme-general-settings',
        'menu_slug' 	=> 'theme-header-settings',
        'capability'	=> 'edit_posts',
        'redirect'		=> false
    ));

    acf_add_options_sub_page(array(
        'page_title' 	=> 'Настройки подвала сайта',
        'menu_title'	=> 'Подвал',
        'parent_slug'	=> 'theme-general-settings',
        'menu_slug' 	=> 'theme-footer-settings',
        'capability'	=> 'edit_posts',
        'redirect'		=> false
    ));
    
// Footer
$builder
    ->setLocation('options_page', '==', 'theme-footer-settings');

$builder
    ->addFlexibleContent('components', ['label' => 'Компоненты', 'button_label' => 'Добавить компонент'])
        ->addLayout(get_field_partial('components.footer.nav-menu-section'), ['label' => 'Меню навигации (Колонки)'])
        ->addLayout(get_field_partial('components.footer.footer-middle'), ['label' => 'Футер (Middle)'])
        ->addLayout(get_field_partial('components.footer.footer-bottom'), ['label' => 'Футер (Bottom)']);
// end Footer

// Header
$builder
    ->setLocation('options_page', '==', 'theme-header-settings');

$builder
    ->addFlexibleContent('components', ['label' => 'Компоненты', 'button_label' => 'Добавить компонент'])
        ->addLayout(get_field_partial('components.header.header-top'), ['label' => 'Шапка (Верхняя часть)']);
// end Header
    `

Thank you in advance :)
