### ISSUE TITLE
License For Commercial Use

### ISSUE THREAD

**Issue by AdamJaggard** [StoutLogic/acf-builder#75]
Am I right in thinking that I couldn't use this in my projects at work unless the source code for those projects is also open source? Just wanted to check. Loving the idea of the project. Looking forward to using it in personal projects regardless.

**Comment by stevep** [comment]
@AdamJaggard This project is Licensed under GPL2 (or later) same as WordPress itself. So if you use WordPress commercially you can use this library commercially in the same way.

- https://github.com/StoutLogic/acf-builder/blob/master/LICENSE
- https://wordpress.org/about/license/

I believe the nuance with the GPL in commercial projects is that if you distribute it, then code must be made available if asked. Don't hold me to that though abridged explanation though :)

Feel free to use in Commercial Projects!

**Comment by AdamJaggard** [comment]
Thanks @stevep. I think that makes sense.
> if you distribute it
I'm guessing that means if I distribute the plugin files in any way I need to make the plugin source code available if it's modified at all which is completely fine. I thought it mean't the custom theme I was developing would also need to be made available.

Appreciate the fast response 👍

**Comment by AdamJaggard** [comment]
For anyone else that might stumble upon this: [https://developer.wordpress.org/themes/getting-started/wordpress-licensing-the-gpl/](https://developer.wordpress.org/themes/getting-started/wordpress-licensing-the-gpl/)

> The GPL only applies to distributed software
