### ISSUE TITLE
Block support

### ISSUE THREAD

**Issue by diaboloshogunate** [StoutLogic/acf-builder#77]
Any plans for adding in support for acf Gutenberg blocks coming out with acf 5.8?

**Comment by EHLOVader** [comment]
Perhaps it is about handling the `acf_register_block` in a fluid call format along with that location information... like build/register a block and add fieldGroups, and their fields to them. Registering and connecting them all of them at once.

I think that would be a nice addition if it can be done well enough.

**Comment by celinebourillot** [comment]
I have just started using blocks in my sage 9 theme and unfortunately this doesn't work :
$newsletterBlock = new StoutLogic\AcfBuilder\FieldsBuilder('newsletter_block');
    $newsletterBlock
        ->addText('title')
        ->addTextarea('intro')
            ->setLocation('block', '==', 'newsletter-block');

add_action('acf/init', function() use ($newsletterBlock) {
    acf_add_local_field_group($newsletterBlock->build());
});

is this wrong or is it just not supported ?

**Comment by Anna-Cantrell** [comment]
> I have just started using blocks in my sage 9 theme and unfortunately this doesn't work :
> $newsletterBlock = new StoutLogic\AcfBuilder\FieldsBuilder('newsletter_block');
> $newsletterBlock
> ->addText('title')
> ->addTextarea('intro')
> ->setLocation('block', '==', 'newsletter-block');
> 
> add_action('acf/init', function() use ($newsletterBlock) {
> acf_add_local_field_group($newsletterBlock->build());
> });
> 
> is this wrong or is it just not supported ?

**This line**
->setLocation('block', '==', 'newsletter-block');

**Needs to be prefaced with 'acf/'**
->setLocation('block', '==', 'acf/newsletter-block');

That'll get it to work.
I know this is old but someone else is bound to come across this page looking for the answer.

**Comment by cheestudio** [comment]
@Anna-Cantrell holy moly...how did you end up finding that!? You were right...that was exactly what I needed! How could this not be documented somewhere?
