### ISSUE TITLE
Cannot use number keys in 'choices' => ['2' => '2 Days', '7' => '7 Days']

### ISSUE THREAD

**Issue by CurtisBelt** [StoutLogic/acf-builder#83]
I cannot use numbered keys, which is useful for things like this:

```php
$builder->addSelect(
    'on_market_since',
    [
        'choices' => [
            '2' => 'Last 2 Days', // builds into 'Last 2 Days' => 'Last 2 Days'
            '7' => 'Last 7 Days', // builds into 'Last 7 Days' => 'Last 7 Days'
        ]
    ]
);

$builder->addSelect(
    'new_construction',
    [
        'choices' => [
            '1' => 'Yes', // builds into 'Yes' => 'Yes'
            '0' => 'No', // builds into 'No' => 'No'
        ]
    ]
);
```
I've tried to make them strings, but PHP's foreach is automatically casting the keys to integer which is leading to your code missing them with the `is_string` check on line 60:

https://github.com/StoutLogic/acf-builder/blob/68e3705505bc85b2d75e8e8d7fbb31181004b4cb/src/ChoiceFieldBuilder.php#L54-L66

If I remove that, everything works correctly. However I understand that isn't the solution though, as you need to support non-associative arrays.

I was planning to submit a PR but I didn't find a simple solution to the problem and had to get back to work. I am curious if anyone has suggestions! Thank you.

**Comment by stevep** [comment]
@CurtisBelt PHP is so weird with arrays. In this case I believe you can achieve what you want by having each choice its own key/val array:

Try:

```php
$builder->addSelect(
    'on_market_since',
    [
        'choices' => [
            ['2' => 'Last 2 Days'], // builds into 'Last 2 Days' => 'Last 2 Days'
            ['7' => 'Last 7 Days'], // builds into 'Last 7 Days' => 'Last 7 Days'
        ]
    ]
);
```

**Comment by CurtisBelt** [comment]
@stevep Oh man, that was right under my nose. Working now, thank you!
